# Generated by Django 3.1.6 on 2021-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
