# Generated by Django 3.1.6 on 2021-02-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_back', '0002_auto_20210212_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
