# Generated by Django 3.1.6 on 2021-02-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_back', '0003_auto_20210215_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
