# Generated by Django 3.1.6 on 2021-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_back', '0004_auto_20210223_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
